services:
  fmusic-discord-bot:
    container_name: fmusic-discord-bot
    image: ghcr.io/alexf0xdev/fmusic-discord-bot:latest
    restart: unless-stopped
    network_mode: host
    environment:
      BOT_TOKEN: '<discord bot token>'
      LAVALINK_HOST: '<lavalink host>'
      LAVALINK_PORT: '<lavalink port>'
      LAVALINK_PASSWORD: '<lavalink password>'
      SENTRY_DSN: '<sentry dsn>'
