version: '3.8'
services:
  fmusic-discord-bot:
    container_name: fmusic-discord-bot
    image: ghcr.io/alexf0xdev/fmusic-discord-bot
    restart: unless-stopped
    environment:
      BOT_TOKEN: 'discord bot token'
      LAVALINK_HOST: 'lavalink host'
      LAVALINK_PORT: 'lavalink port'
      LAVALINK_PASSWORD: 'lavalink password'
      SENTRY_DSN: 'sentry dsn'
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
