services:
  fmusic-discord-bot:
    container_name: fmusic-discord-bot
    image: ghcr.io/alexf0xdev/fmusic-discord-bot:latest
    restart: always
    environment:
      BOT_TOKEN: '<BOT_TOKEN>'
      BOT_VOLUME: 40
      LAVALINK_ID: '<LAVALINK_ID1;LAVALINK_ID2>'
      LAVALINK_HOSTS: '<LAVALINK_HOST1;LAVALINK_HOST2>'
      LAVALINK_PORTS: '<LAVALINK_PORT1;LAVALINK_PORT2>'
      LAVALINK_PASSWORDS: '<LAVALINK_PASSWORDS>'
    networks:
      - fmusic-discord-bot
networks:
  fmusic-discord-bot:
    name: fmusic-discord-bot
