services:
  fmusic-discord-bot:
    container_name: fmusic-discord-bot
    image: ghcr.io/alexf0xdev/fmusic-discord-bot:latest
    restart: unless-stopped
    environment:
      BOT_TOKEN: '<discord bot token>'
      BOT_VOLUME: 40
      LAVALINK_IDS: '<lavalink ids>'
      LAVALINK_HOSTS: '<lavalink hosts>'
      LAVALINK_PORTS: '<lavalink ports>'
      LAVALINK_PASSWORDS: '<lavalink passwords>'
      SENTRY_DSN: '<sentry dsn>'
